from __future__ import annotations
import streamlit as st
import pandas as pd
from engine import run

st.set_page_config(page_title="GoldenSet Factory · Sample I/O", page_icon="↔", layout="wide")

st.markdown("""
<style>
html,body,[class*="css"],.stApp{font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","SF Pro Text","Helvetica Neue",Helvetica,Arial,sans-serif;color:#1d1d1f}.stApp{background:linear-gradient(180deg,#fff 0%,#fbfbfd 100%)}.block-container{max-width:1380px;padding-top:2.2rem;padding-bottom:5rem}#MainMenu,footer,header{visibility:hidden}.hero{background:radial-gradient(circle at 8% 0%,rgba(0,113,227,.14),transparent 32%),linear-gradient(155deg,#fff,#f5f5f7);border:1px solid #e8e8ed;border-radius:34px;padding:44px 48px;margin-bottom:22px;box-shadow:0 18px 48px rgba(0,0,0,.04)}.eyebrow{color:#0071e3;font-size:.75rem;font-weight:750;letter-spacing:.12em;text-transform:uppercase}.hero h1{font-size:3rem;letter-spacing:-.055em;line-height:1;margin:.55rem 0 .7rem}.hero p{color:#6e6e73;max-width:920px;font-size:1.04rem;line-height:1.55}.card{background:#fff;border:1px solid #e8e8ed;border-radius:26px;padding:22px;box-shadow:0 8px 24px rgba(0,0,0,.025)}.step{color:#0071e3;font-size:.69rem;font-weight:760;letter-spacing:.1em;text-transform:uppercase}.big{font-size:1.35rem;font-weight:720;letter-spacing:-.03em;margin:.35rem 0}.muted{color:#6e6e73;font-size:.9rem;line-height:1.5}.arrow{text-align:center;font-size:2rem;color:#0071e3;padding-top:40px}.badge{display:inline-block;background:#f5f5f7;border:1px solid #e8e8ed;border-radius:999px;padding:7px 10px;margin:0 6px 6px 0;color:#515154;font-size:.78rem}</style>
<div class="hero"><div class="eyebrow">GoldenSet Factory · Sample Input → Output</div><h1>Watch one production-style failure become a benchmark candidate.</h1><p>This example starts with a raw feedback item, then shows the cluster, novelty, difficulty, coverage-gap bonus, and final candidate decision generated by the benchmark-lifecycle pipeline.</p></div>
""",unsafe_allow_html=True)

@st.cache_data(show_spinner=False)
def load(): return run(seed=42,n_feedback=2500,target_size=120)

feedback,benchmark,candidates,coverage,selected,manifest,metrics=load()
idx=st.slider("Candidate example",0,min(50,len(candidates)-1),0)
row=candidates.sort_values("selection_score",ascending=False).iloc[idx]
selected_ids=set(selected.feedback_id)
coverage_row=coverage[coverage.failure_mode==row.failure_mode].iloc[0]
selected_row=selected[selected.feedback_id==row.feedback_id]
final_score=float(selected_row.final_score.iloc[0]) if len(selected_row) else float(row.selection_score)
coverage_bonus=float(selected_row.coverage_bonus.iloc[0]) if len(selected_row) else (0.22 if coverage_row.status=="underrepresented" else 0.0)

input_cols=["feedback_id","failure_mode","severity","source","tool","recoverable","summary"]
output_df=pd.DataFrame([{"cluster":int(row.cluster),"novelty_score":row.novelty_score,"difficulty_score":row.difficulty_score,"coverage_status":coverage_row.status,"coverage_ratio":coverage_row.coverage_ratio,"coverage_bonus":coverage_bonus,"final_score":final_score,"selected_as_candidate":row.feedback_id in selected_ids,"human_approval_required":True}])

st.markdown("### Example flow")
c1,c2,c3=st.columns([1,0.12,1])
with c1:
    st.markdown('<div class="card"><div class="step">1 · Sample input</div><div class="big">Production-style failure evidence</div><div class="muted">A real adapter could map incidents, human overrides, rollbacks, escaped defects, SARIF findings, agent traces, or service tickets into this normalized record.</div></div>',unsafe_allow_html=True)
    st.dataframe(pd.DataFrame([{k:row[k] for k in input_cols}]),hide_index=True,use_container_width=True)
with c2: st.markdown('<div class="arrow">→</div>',unsafe_allow_html=True)
with c3:
    st.markdown('<div class="card"><div class="step">2 · Benchmark output</div><div class="big">Candidate score + governance boundary</div><div class="muted">Selection creates a candidate case only. Trusted-benchmark promotion remains human-approved.</div></div>',unsafe_allow_html=True)
    st.dataframe(output_df,hide_index=True,use_container_width=True)

st.markdown("### What the factory did")
st.markdown('<span class="badge">normalize feedback</span><span class="badge">TF-IDF</span><span class="badge">cluster</span><span class="badge">novelty vs benchmark</span><span class="badge">difficulty</span><span class="badge">coverage gap</span><span class="badge">deduplicate</span><span class="badge">human approval</span>',unsafe_allow_html=True)

st.markdown("### Example interpretation")
if row.feedback_id in selected_ids:
    st.success(f"**{row.feedback_id} becomes a candidate golden case.** Failure mode **{row.failure_mode}** has coverage status **{coverage_row.status}**, novelty {row.novelty_score:.3f}, and difficulty {row.difficulty_score:.3f}. It still requires expert approval before entering the next trusted benchmark version.")
else:
    st.info(f"**{row.feedback_id} is not selected in the current target budget.** It remains available as feedback evidence, but higher-scoring, more novel, more difficult, or more underrepresented cases consume the candidate-set budget first.")

st.caption("All failures and benchmark cases are synthetic. This page demonstrates the production-feedback-to-benchmark input/output contract and explicitly keeps human approval in the loop.")
